[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]
    NPM_FLAGS = "--include=dev"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/SkyeDocxPro/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200